name: Release obsidian plugin

on:
    workflow_dispatch:
        inputs:
            bump:
                default: false
                description: "Bump version based on semantic release"
                type: boolean
                required: false
            beta:
                default: false
                description: "Make a beta release"
                type: boolean
                required: false
    push:
        tags:
            - "*"
permissions:
    contents: write

jobs:
    release:
        if: (github.event_name == 'push') || (github.event_name == 'workflow_dispatch' && !inputs.bump)
        uses: mara-li/reusable-workflows/.github/workflows/obsidian-plugin-release.yaml@main

        with:
            PLUGIN_NAME: open-plugin-settings
            CACHE: "bun"
        secrets:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    bump-version-and-release:
        if: ${{ inputs.bump || false }}
        uses: mara-li/reusable-workflows/.github/workflows/obsidian-plugin-bump-version.yaml@main
        with:
            PLUGIN_NAME: open-plugin-settings
            BETA: ${{ inputs.beta || false}}
            CACHE: "bun"
        secrets:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
